<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

/**
 * A single-use, short-lived passwordless login link generated by an admin for a
 * specific user. Only the token hash is stored — the raw token is returned once
 * at creation and embedded in the URL. Consuming the link logs the holder in as
 * {@see self::$user_id} and burns the link (sets `used_at`).
 */
class MagicLoginLink extends Model
{
    /** Links expire this many minutes after creation. */
    public const EXPIRY_MINUTES = 30;

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'user_id',
        'created_by_user_id',
        'token_hash',
        'expires_at',
        'used_at',
    ];

    protected function casts(): array
    {
        return [
            'expires_at' => 'datetime',
            'used_at' => 'datetime',
        ];
    }

    protected static function boot(): void
    {
        parent::boot();

        static::creating(function (self $model) {
            if (empty($model->id)) {
                $model->id = (string) Str::uuid7();
            }
        });
    }

    /**
     * Mint a new link for the target user. Returns the persisted model plus the
     * RAW token (never stored) the caller embeds in the URL.
     *
     * @return array{link: self, token: string}
     */
    public static function generate(User $target, ?User $admin): array
    {
        $token = Str::random(48);

        $link = self::create([
            'user_id' => $target->id,
            'created_by_user_id' => $admin?->id,
            'token_hash' => self::hashToken($token),
            'expires_at' => now()->addMinutes(self::EXPIRY_MINUTES),
        ]);

        return ['link' => $link, 'token' => $token];
    }

    public static function hashToken(string $token): string
    {
        return hash('sha256', $token);
    }

    public function isUsable(): bool
    {
        return $this->used_at === null && $this->expires_at->isFuture();
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }
}
